version: '3'

services:
  'api':
    build: ./
    ports:
     - "4201:4201"
    volumes:
     - .:/src
    links:
      - db
  'db':
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  'web':
    build: ./web
    working_dir: /src
    volumes:
     - ./web:/src
    ports:
     - "4200:4200"
